### PR TITLE
Added ability to upload attachments to an issue.

### PR DESCRIPTION
**Pull request by syntruth**
Code is based on, but rewritten from:

https://github.com/Hawatel/jira-ruby/blob/master/lib/jira/resource/attachment.rb

Also removed unneeded .ruby-version file.

I don't have have any tests for this, though have verified it works with our local Jira installation.

### CODE REVIEW

**Comment by SimonMiaou** [comment]
I use a similar implementation that also works for me.
However, I will take a look how to test the code as it would be a big plus.

**Comment by SimonMiaou** [comment]
@syntruth Could you merge master in your banch? It should fix the failing tests.
Also you removed some extra code (the `meta` method), could you bring it back?

I would like this PR to be merged for the next release

**Comment by syntruth** [comment]
Will do when I get some time during the weekend or early next week. :)

**Comment by syntruth** [comment]
I goofed and merged my Watcher branch into this as well, but I've confirmed that it works as well. I was going to do a separate pull request for that feature next week at some point.

**Comment by syntruth** [comment]
Will look into these tests again, too. :| I've never used RSpec before, just Minitest, so I have some reading up to do.

**Comment by SimonMiaou** [comment]
@syntruth Any update? I'm currently looking to be able to test the attachments 😉

**Comment by SimonMiaou** [comment]
I took out the original code with some edits and did a PR #244 
I will close this one as the tests are red and it contains unrelated code

**Comment by syntruth** [comment]
Sorry for going silent. I was re-assigned to another project and never got time to come back to write the tests. :(  For what it's worth, however, the file attachment code has been working flawlessly on our production server, handling hundreds of file attachments each day. Has the official gem been updated yet? I'm sure we'd like to move to that instead of our locally patched version. :)

Sorry for the headaches!

**Comment by SimonMiaou** [comment]
I hope publish the new version later today 😉 
We were also working with the same patch until now.

**Pull request closed without merging**
