### PR TITLE
Assign certificate store default paths to the Net::HTTP connection

### PR DESCRIPTION
**Pull request by andrewburnheimer**
This fix alleviated the "SSL_connect returned=1 errno=0 state=SSLv3 read
server certificate" error occuring on a CentOS release 6.4 (Final) Linux
system.

### CODE REVIEW

**Comment by jufemaiz** [comment]
@bobbrodie can you confirm the methodology to generate rsakey.pem ? Cloned and running rspec but obviously there's another step.

**Comment by bobbrodie** [comment]
@jufemaiz That's correct - you need to generate a consumer key and public certificate to be able to fully test with JIRA running. This is documented in https://github.com/sumoheavy/jira-ruby#using-the-api-gem-in-your-rails-application, but I can see how it's a little vague - it might be worth swapping "...in their respective rake tasks" with the actual tasks.

**Comment by jufemaiz** [comment]
@bobbrodie all good :) found after some digging but if you wanted to, add "rsakey.pem" to the docs that includes notes on generation of key for easy searching?

**Comment by bobbrodie** [comment]
That's a great idea! I've added #154 so I don't lose track.

**Pull request closed without merging**
