### PR TITLE
Adding feature to retrieve all the watchers from a specific issue

### PR DESCRIPTION
**Pull request by samanthakem**
1. Added a Watcher object.
2. Added a "all" function in order to retrieve the watchers from a specific issue.

### CODE REVIEW

**Comment by samanthakem** [comment]
Anyone to review this?

**Comment by bobbrodie** [comment]
@samanthakem what a great feature! Can you add/update tests for this so we can merge it in?

**Comment by AgarFu** [comment]
Hey seems that all the tests are passing and there are no conflicts with master, can someone please review and merge this feature?

**Comment by SimonMiaou** [comment]
But there is no tests for this feature...

**Comment by AgarFu** [comment]
I see, I'll try to add some tests then in another branch

**Comment by SimonMiaou** [comment]
That would be awesome

**Comment by SimonMiaou** [comment]
Hey @AgarFu 
Any chance you got time to add tests?

**Comment by samanthakem** [comment]
I will try to work on this feature tests asap, finally.

**Comment by samanthakem** [comment]
@SimonMiaou could you check the test I created?

**Comment by samanthakem** [comment]
Any updates on my review request?

**Comment by arkadiyt** [comment]
I was just looking for this feature, thanks for implementing!

Possible to get a version bump / release for this?

**Comment by SimonMiaou** [comment]
@arkadiyt Done 😉

**Comment by arkadiyt** [comment]
Thanks!

**Pull request merged**
