### PR TITLE
Fix user all endpoint

### PR DESCRIPTION
**Pull request by starfish719**
https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-users/#api-rest-api-2-users-search-get

typo? 🤔

### CODE REVIEW

**Comment by starfish719** [comment]
@SimonMiaou can you take a look here, please 🙏

**Review by SimonMiaou — APPROVED** [review]
Will merge and release a new gem version later today or this weekend

**Comment by starfish719** [comment]
@SimonMiaou thank you for your review :)
I'm looking forward to it being released.

**Comment by starfish719** [comment]
@SimonMiaou 
fix #260 

isn't it ?

**Pull request merged**
