### PR TITLE
cookie based authentication implemented

### PR DESCRIPTION
**Pull request by SiarheiFedartsou**
Hi! There are some cases when basic auth doesn't work(https://answers.atlassian.com/questions/203977/jira-api-basic-authentication-not-work). Cookie-based authentication(https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-example-cookie-based-authentication) works fine in such cases, so I propose to add such authentication to this library.

### CODE REVIEW

**Comment by SiarheiFedartsou** [comment]
It seems that build error is not caused by my PR...

**Comment by bobbrodie** [comment]
@SiarheiFedartsou Please pull the latest master into your fork and re-push. There was a dependency issue with one of the Gems and older versions of Ruby.

**Comment by SiarheiFedartsou** [comment]
@bobbrodie done!

**Comment by bobbrodie** [comment]
@SiarheiFedartsou awesome!

**Pull request merged**
