### PR TITLE
Update agile.rb to allow options for boards

### PR DESCRIPTION
**Pull request by kalinon**
Passed options to agile all method so pagination can be accessed on boards

### CODE REVIEW

**Comment by rmf34** [comment]
makes sense, is there any options checking we want to do? and a test?

**Comment by SimonMiaou** [comment]
Hi @kalinon ,
Could you take a look at @rmf34 comment? I believe having some checks would be helpful for the users when updating the gem in the future

**Comment by kalinon** [comment]
@SimonMiaou sorry its been awhile (almost a year) and i dont work at Optanix anymore, so i no longer have access to this fork.

**Comment by SimonMiaou** [comment]
Please someone reopen a PR if this feature is wished, closing this one for now

**Pull request closed without merging**
