### PR TITLE
IssueCount

### PR DESCRIPTION
**Pull request by Simwar**
Hello,

I'm using your gem but I didn't found a way to only get the number of issues without getting all the content.
The REST API has always the field "Total" filled when doing a query so I thought I could make an other class to only return this number.
I'm new to Ruby so maybe I didn't do it the best way.

Tell me if this is a good idea or not :)

Simon

### CODE REVIEW

**Comment by bobbrodie** [comment]
@Simwar I noticed there aren't any spec updates for this - can you check that out and add any tests that need to be added?

**Comment by Simwar** [comment]
@bobbrodie sorry for the delay.

I added a file in the specs. Tell me if you think something looks wrong.

**Comment by Simwar** [comment]
Also, looks there is a dependency error in the gems.

**Comment by bobbrodie** [comment]
@Simwar I updated master to require Ruby 2.3.1 and the latest head on Travis-CI, however after merging your PR the tests on your branch failed. I have reverted the change until the tests have been updated to pass. As an additional note, please pull master from the main repo into your fork so you have the latest Travis config.

**Comment by Simwar** [comment]
Hello,

Sorry this process is new for me. I'll check this out ! Thank you for the try though.

**Pull request merged**
