### PR TITLE
Attachment download contents

### PR DESCRIPTION
**Pull request by marlinpierce**
Adds methods to attachments to download the attachment contents.

### CODE REVIEW

**Comment by morphine00** [comment]
Neat, thanks! The only note I have is that it's probably preferable to return a Tempfile because the contents may be quite large and they'll otherwise be kept in memory.

**Comment by marlinpierce** [comment]
@morphine00 I provided the `download_file` method to return a file IO object.  This should allow you to read in blocks, or read the beginning of the file, whatever you would do to avoid reading the whole contents into a string object in memory..  Assuming the `URI.open` streams the input, it should provided the IO without reading the string contents into memory and without saving to a file, reading as it is available from the network interface.

**Comment by morphine00** [comment]
Ah, I missed that detail, my apologies.

**Comment by bobbrodie** [comment]
@marlinpierce I'm so sorry, I know it's been a while. When you have a moment, could you update your PR to resolve the conflicts? If you can't get to it now I completely understand, and in that case I'll make a new PR with your changes. I'd like to get this in for you. Thanks!

**Comment by marlinpierce** [comment]
@bobbrodie the merge conflict is resolved.  I'm looking forward to the `0.2.4` release.

**Review by bobbrodie — APPROVED** [review]

**Comment by bobbrodie** [comment]
Sounds great, thanks @marlinpierce. I've started a thread [here](https://github.com/sumoheavy/jira-ruby/issues/429) about the next version. I think that being since it's been so long, and Ruby <= 3.0 are no longer supported, it probably makes sense to release a 3.0.0 version of the gem without those versions included.

**Pull request merged**
