### PR TITLE
Add BoardConfiguration API

### PR DESCRIPTION
**Pull request by wireframe**
Why?
Allow for lookup of configuration information for a specific board.

See JIRA API documentation:
https://developer.atlassian.com/cloud/jira/software/rest/#api-rest-agile-1-0-board-boardId-configuration-get

Completes #316

### CODE REVIEW

**Comment by wireframe** [comment]
@bobbrodie are you the point of contact for this repo for contributions?  Anything specific the SUMO Heavy team is looking for from contributors or an ETA of review/feedback on PR's?

**Comment by bobbrodie** [comment]
Hey @wireframe we're the repo owners but there are a few others that can approve/merge/release the gem. Feel free to @-mention me in the future and I'll take a look. Due to Jira changes and it being easier to integrate, things have been slow for the gem but we know that there are still some folks outside of us using it.

We'll take a look at this feature this week - thanks for the contribution!

**Comment by SimonMiaou** [comment]
Hi @wireframe 
It looks like you forgot this PR?

**Comment by wireframe** [comment]
> Could you add the specs for the change?

@bobbrodie apologies for the delay!  Specs have been added!

**Comment by SimonMiaou** [comment]
Thank you @wireframe

**Pull request merged**
