### PR TITLE
Net::HTTP::Proxy is obsolete

### PR DESCRIPTION
**Pull request by lusty**
This change fixes issue https://github.com/sumoheavy/jira-ruby/issues/344

### CODE REVIEW

**Comment by coen-hyde** [comment]
I disagree that the capability of `Net::HTTP.new` to pull the proxy from the `HTTP_PROXY ` environment variable makes the specification of proxy here obsolete. This removes the ability to make Jira calls via a specific proxy.

**Comment by dblessing** [comment]
@coen-hyde `Net::HTTP::Proxy` is definitely obsolete per https://apidock.com/ruby/Net/HTTP/Proxy/class. But I understand what you're saying about this change. This change should utilize the same params and send them to `Net::HTTP#new` since it now supports the same params as `Net::HTTP::Proxy#new`.

**Comment by SimonMiaou** [comment]
@lusty Any chance that you look at this? It would be helpful to have the gem move forward

**Comment by marlinpierce** [comment]
@SimonMiaou This is replaced by [PR 419](https://github.com/sumoheavy/jira-ruby/pull/419) and PR 363 can be closed.

**Pull request closed without merging**
