### PR TITLE
Mavenlink solutions master

### PR DESCRIPTION
**Pull request by kalinon**

### CODE REVIEW

**Comment by bobbrodie** [comment]
This is incredible -- we'll work on getting these checked out. Thank you!

**Comment by kalinon** [comment]
yeah sorry about all the combined stuff! But pulled in all the relevant forks.

**Comment by bobbrodie** [comment]
This all looks awesome -- I just have one question. To anyone looking at this, would you rather merge and then bump to 1.6.0, or bump in the commit and then merge?

**Comment by kalinon** [comment]
Im cool with 

> This all looks awesome -- I just have one question. To anyone looking at this, would you rather merge and then bump to 1.6.0, or bump in the commit and then merge?

I'm cool with either. Been using the merged changes and everything is going swimmingly.

**Pull request merged**
