### PR TITLE
Add expand option to `Issue.jql`

### PR DESCRIPTION
**Pull request by dillonkearns**
This fixes issue #93.

### CODE REVIEW

**Comment by blainesch** [comment]
:+1:

**Comment by tbilou** [comment]
I've been using this patch on my app without any problems and would love if you guys could merge it.

**Comment by dillonkearns** [comment]
Yes, I've been using it as well, would love to see this merged @bobbrodie!

**Comment by bobbrodie** [comment]
Added in 1959b1c93d46869f403c355b29f6907cf1b28463

**Pull request closed without merging**
