### PR TITLE
Adding Issue instance methods

### PR DESCRIPTION
**Pull request by pescetto**
I would like to make it easier for end-users to work with the issue object. It's the most used object in our organization and we've found these to be incredibly helpful and will help dry up the code in the client's repos.

### CODE REVIEW

**Comment by SimonMiaou** [comment]
Hey @pescetto 
This seems like awesome features.
Could you write some tests to make sure it is working and that it will not break easily if someone want to improve them?

**Comment by pescetto** [comment]
Thanks @SimonMiaou I'm currently working on a project right now, but I'll add tests and rebase.

**Comment by SimonMiaou** [comment]
Ping @pescetto 
I think you forgot about this, up to still write some tests?

**Comment by pescetto** [comment]
@SimonMiaou Yeah, sorry, this definitely fell off my radar. Let me take a look at it this week and get them written.

Thank you,
~ Mike

**Comment by pescetto** [comment]
I'm sorry @SimonMiaou I just don't have the time for this right now. I can reopen this PR with tests if this comes back up.

**Pull request closed without merging**
